# Generated by Django 5.1.4 on 2024-12-13 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ndate', models.DateField(null=True)),
                ('title', models.CharField(max_length=250)),
            ],
        ),
    ]
